language: python
python:
  - "2.7"

before_install:
  - "python setup.py sdist"

install:
  - "pip install --use-mirrors nose"
  - "pip install dist/minion-backend-0.1.tar.gz --use-mirrors"

# command to run tests
script:
  nosetests
