language: python
python:
  - "2.7"

before_install:
  - "python setup.py sdist"
  - "sudo apt-get install stunnel"

install:
  - "pip install --use-mirrors nose"
  - "pip install dist/minion-backend-0.1.tar.gz --use-mirrors"

# tells travis to start mongodb
services:
  - mongodb
  - rabbitmq

# tells travis to start these services before running script
before_script:
  - "scripts/minion-scan-worker &"
  - "sleep 3"
  - "scripts/minion-state-worker &"
  - "sleep 3"
  - "scripts/minion-plugin-worker &"
  - "sleep 3"
  - "scripts/minion-backend-api runserver &"
  - "sleep 3"
  - "scripts/minion-create-plan plans/basic.plan"

# command to run tests
script:
  nosetests
